###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: diag2017-memcached

    redis:
      image: redis:alpine
      container_name: diag2017-redis

    clickhouse:
      image: yandex/clickhouse-server:latest
      container_name: diag2017-clickhouse

    mariadb:
      image: mariadb:10.1
      container_name: diag2017-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=qwe123
        - MYSQL_DATABASE=diag
        - MYSQL_USER=drag
        - MYSQL_PASSWORD=qwe123
      ports:
        - "6670:3306"

    webserver:
      image: nginx:alpine
      container_name: diag2017-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7897:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: diag2017-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

