parameters:


  storage:
    Sqlite:
      database: :memory:
      log_table: table_log
      cleanup_interval: 'P1M'
    Clickhouse:
      host: 127.0.0.1:8123
      database: default
      user: default
      password: ''