imports:
    - { resource: parameters/development/database.php }

parameters:
  storage:
    sqlite:
      database: :memory:
      log_table: table_log
      cleanup_interval: 'P1M'
    clickhouse:
      host: 127.0.0.1:8123
      database: default
      user: default
      password: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Diag\Controller\:
            resource: '../src/Controller/*'

#properties:
#    storage:
#      Sqlite:
#        database: /tmp/default.sqlite
#        log_table: table_log
#        cleanup_interval: 'P1M'
#      Clickhouse:
#        host: 127.0.0.1:8123
#        database: default
#        user: default
#        password: ''