
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Diag\Controller\:
            resource: '../src/Controller/*'




    Diag\Storage\Clickhouse:
      arguments:
        $logTable: 'log_table'
    pdo:
      class: \PDO
      arguments: ['%database.dsn%']

    Diag\Storage\Sqlite:
      arguments: ['@pdo', 'log_table']

