imports:
    - { resource: config-clickhouse.yml }
    - { resource: parameters/development/db.yml }
    - { resource: config-common.yml }




#properties:
#    storage:
#      Sqlite:
#        database: /tmp/default.sqlite
#        log_table: table_log
#        cleanup_interval: 'P1M'
#      Clickhouse:
#        host: 127.0.0.1:8123
#        database: default
#        user: default
#        password: ''